services:
  springboot_app:
    build: .
    container_name: springboot_app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./env.properties:/app/env.properties  # Mount env.properties into the container
    networks:
      - spring-network
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=replace-me
      - POSTGRES_USER=replace-me
      - POSTGRES_DB=spring
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
